version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  mongo-data:
